# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file cap01/pom.xml ; mvn -B package --file cap02/pom.xml; mvn -B package --file cap03/pom.xml; mvn -B package --file cap04/pom.xml; mvn -B package --file cap05/pom.xml; mvn -B package --file cap06/pom.xml; mvn -B package --file cap07/pom.xml; mvn -B package --file cap08/pom.xml; mvn -B package --file cap09/pom.xml
